// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_EntryType = {__proto__:null,"@string":60, "@preamble":80, "@comment":82}
export const parser = LRParser.deserialize({
  version: 14,
  states: "(vQYQPOOOhQPO'#C_OmQPO'#CjOrQPO'#CkOwQPO'#CmOOQO'#Cy'#CyOOQO'#Cq'#CqQYQPOOO|QPO,58yO!RQPO,59UO!aOQO'#DWOOQO,59V,59VO!iQPO,59XOOQO-E6o-E6oOOQO'#Ca'#CaO!nQPO1G.eO!sOSO'#CdO#ROWO'#CfOOQO'#Ch'#ChOOQO'#Cc'#CcO#aQPO'#CbO#lQPO1G.pOOQO,59r,59rO#qOPO,59rOOQO'#Cn'#CnO#vQPO1G.sO!RQPO7+$POOOO'#DO'#DOOOOO'#Cr'#CrO$OOSO,59OOOQO,59O,59OOOOO'#DS'#DSOOOO'#Cs'#CsO$^OWO,59QOOQO,59Q,59QO!RQPO'#CtO$lQPO,58|OOQO7+$[7+$[OOQO1G/^1G/^O$wQPO7+$_O%PQPO7+$_OOQO7+$_7+$_O%XQPO<<GkOOOO-E6p-E6pOOQO1G.j1G.jOOOO-E6q-E6qOOQO1G.l1G.lOOQO,59`,59`OOQO-E6r-E6rOOQO'#Cp'#CpO%^QPO'#CoOOQO,59a,59aOOQO<<Gy<<GyO%cQPO<<GyOOQO-E6s-E6sOOQOAN=VAN=VO!RQPO,59ZOOQOAN=eAN=eP%kQPO'#CuOOQO1G.u1G.u",
  stateData: "%p~OlOSPOS~OSSOnPOxQOyRO~OoWO~OoXO~OoYO~Oo[O~Op^O~OZcOo`OpbOuaO~O`gOtfO~OphO~OqjO~OXkOo`OskOtnO~OXoOo`OurOwoO~O]sOtUX{UX~OtuO~OtvO~OtyO{wO~OXkOo`OskOt|O~OXoOo`Ou!OOwoO~O]sOtUa{Ua~Op!ROt!UO~Ot!UO{!VO~Ot!XO~Oq!YO~Op!ROt!ZO~Op!RO~O",
  goto: "$W{PPP|P!Q!T!^!fP!tP!tP||P|!z!}#S#X#_#e#k#qPPP#wPPPP#{PPP$PPPP$TTTOVR_WQeXQzjR!]!YUdXj!YR!PsWcXjs!YSk`mToaqXcXjs!YRi[V!Tw!V![V!Sw!V![QVOR]VQm`R{mQqaR}qQtdR!QtQxiR!WxTUOVTl`mTpaqRZR",
  nodeNames: "⚠ Comment File StringEntry EntryType StringName Value ValueAtom BracedValue Escape QuotedValue Number StringRef Concat PreambleEntry CommentEntry CommentBody Entry EntryKey Field FieldName",
  maxTerm: 43,
  skippedNodes: [0,1],
  repeatNodeCount: 5,
  tokenData: "6x_RqOX#YXY&XYZ&XZ]#Y]^&X^p#Ypq&Xqr#Yrs'lst(_tu#Yuv)]v|#Y|}-t}!Q#Y!Q![.r![!_#Y!_!`/v!`!b#Y!b!c0t!c!}3Q!}#O#Y#O#P4q#P#R#Y#R#S3Q#S#T#Y#T#o3Q#o#p5z#p#q#Y#q#r6_#r;'S#Y;'S;=`&R<%lO#Y^#cZ`QsSwWOr#Yrs$Us#O#Y#O#P$u#P#o#Y#o#p$u#p#q#Y#q#r%d#r;'S#Y;'S;=`&R<%lO#YU$]W`QsSO#O$U#O#P$u#P#o$U#o#p$u#p#q$U#r;'S$U;'S;=`%^<%lO$UQ$zS`QO#q$u#r;'S$u;'S;=`%W<%lO$uQ%ZP;=`<%l$uU%aP;=`<%l$UW%iUwWOr%ds#O%d#P#o%d#p;'S%d;'S;=`%{<%lO%dW&OP;=`<%l%d^&UP;=`<%l#Y_&db`QsSwWlPOX#YXY&XYZ&XZ]#Y]^&X^p#Ypq&Xqr#Yrs$Us#O#Y#O#P$u#P#o#Y#o#p$u#p#q#Y#q#r%d#r;'S#Y;'S;=`&R<%lO#Y_'uWuX`QsSO#O$U#O#P$u#P#o$U#o#p$u#p#q$U#r;'S$U;'S;=`%^<%lO$U_(jZ`Q]PsSwWOr#Yrs$Us#O#Y#O#P$u#P#o#Y#o#p$u#p#q#Y#q#r%d#r;'S#Y;'S;=`&R<%lO#Y_)h]PP`QsSwWOY)]YZ#YZr)]rs*as#O)]#O#P+]#P#o)]#o#p+]#p#q)]#q#r,n#r;'S)];'S;=`-n<%lO)]V*jZPP`QsSOY*aYZ$UZ#O*a#O#P+]#P#o*a#o#p+]#p#q*a#q#r+y#r;'S*a;'S;=`,h<%lO*aR+dVPP`QOY+]YZ$uZ#q+]#q#r+y#r;'S+];'S;=`,b<%lO+]P,OSPPOY+yZ;'S+y;'S;=`,[<%lO+yP,_P;=`<%l+yR,eP;=`<%l+]V,kP;=`<%l*aX,uZPPwWOY,nYZ%dZr,nrs+ys#O,n#O#P+y#P#o,n#o#p+y#p;'S,n;'S;=`-h<%lO,nX-kP;=`<%l,n_-qP;=`<%l)]_.PZ{P`QsSwWOr#Yrs$Us#O#Y#O#P$u#P#o#Y#o#p$u#p#q#Y#q#r%d#r;'S#Y;'S;=`&R<%lO#Y_.}]`QZPsSwWOr#Yrs$Us!Q#Y!Q![.r![#O#Y#O#P$u#P#o#Y#o#p$u#p#q#Y#q#r%d#r;'S#Y;'S;=`&R<%lO#Y_0RZqP`QsSwWOr#Yrs$Us#O#Y#O#P$u#P#o#Y#o#p$u#p#q#Y#q#r%d#r;'S#Y;'S;=`&R<%lO#Y_0}^`QsSwWOr#Yrs$Us!c#Y!c!}1y!}#O#Y#O#P$u#P#T#Y#T#o1y#o#p$u#p#q#Y#q#r%d#r;'S#Y;'S;=`&R<%lO#Y_2U^`QSPsSwWOr#Yrs$Us!c#Y!c!}1y!}#O#Y#O#P$u#P#T#Y#T#o1y#o#p$u#p#q#Y#q#r%d#r;'S#Y;'S;=`&R<%lO#Y_3]f`QsSpPwWOr#Yrs$Us}#Y}!O3Q!O!P3Q!P!Q3Q!Q![3Q![!]3Q!]!c#Y!c!}3Q!}#O#Y#O#P$u#P#R#Y#R#S3Q#S#T#Y#T#o3Q#o#p$u#p#q#Y#q#r%d#r;'S#Y;'S;=`&R<%lO#Y^4vU`QO#q5Y#q#r5m#r;'S5Y;'S;=`5r;=`<%l5m<%lO5Y^5aS`QX[O#q$u#r;'S$u;'S;=`%W<%lO$u[5rOX[^5wPX[;=`<%l5Y_6RSo]`QO#q$u#r;'S$u;'S;=`%W<%lO$u_6fUtVwWOr%ds#O%d#P#o%d#p;'S%d;'S;=`%{<%lO%d",
  tokenizers: [0, 1, 2, 3],
  topRules: {"File":[0,2]},
  specialized: [{term: 4, get: (value) => spec_EntryType[value] || -1}],
  tokenPrec: 0
})
