// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_EntryType = {__proto__:null,"@string":64, "@preamble":88, "@comment":90}
export const parser = LRParser.deserialize({
  version: 14,
  states: ")fQYQPOOOhQPO'#C_OhQPO'#ClOpQPO'#CmOhQPO'#CnOOQO'#C{'#C{OOQO'#Cr'#CrQYQPOOOOQO'#Ca'#CaOuQPO,58yOzQPO,59WO!YOQO'#D[OOQO,59X,59XO!hQSO,59YOOQO-E6p-E6pOOQO'#Cb'#CbO!mQPO1G.eO!rOQO'#CeO#QOWO'#CgOOQO'#Ci'#CiOOQO'#Cd'#CdO#`QPO'#CcO#nQPO1G.rOOOO'#D]'#D]OOOO'#Cv'#CvO#vOQO,59vOOQO,59v,59vOOQO'#Co'#CoO$UQPO1G.tOzQPO7+$POOOO'#DR'#DROOOO'#Cs'#CsO$aOQO,59POOQO,59P,59POOOO'#DV'#DVOOOO'#Ct'#CtO$oOWO,59ROOQO,59R,59ROzQPO'#CuO$}QPO,58}OOQO'#Ck'#CkOOQO7+$^7+$^OOOO-E6t-E6tOOQO1G/b1G/bO%]QPO7+$`O%hQPO7+$`OOQO7+$`7+$`O#nQPO<<GkOOOO-E6q-E6qOOQO1G.k1G.kOOOO-E6r-E6rOOQO1G.m1G.mOOQO,59a,59aOOQO-E6s-E6sOOQO'#Cq'#CqO%sQPO'#CpOOQO,59c,59cOOQO<<Gz<<GzO%]QPO<<GzOOQO-E6u-E6uOOQOAN=VAN=VOzQPO,59[OOQOAN=fAN=fP%xQPO'#CwOOQO1G.v1G.v",
  stateData: "&T~OnOSPOS~OSSOpPO|QO}RO~OqWOrWO~OqZO~Os_O~O[dOqaOscOxbO~OYgOqaOwjO!QgO~O!RkO~OtmO~OYnOqaOvnOwqO~OYrOqaOxuOzrO~O^vOwVX{VX!SVX~OwxO{xO~OYgOqaOw{O!QgO~OwxO{xO!S|O~OYnOqaOvnOw!RO~OYrOqaOx!TOzrO~O^vOwVa{Va!SVa~Os!WOwxO{xO~OwxO{xO!S![O~Ot!_O~Os!WO~OYvz!Qz~",
  goto: "%U!QPPP!RP!V!`!c!l!tP#WP#WP#^!R!R!R#n#q#v#{$R$X$_$e$kPPP$qPPPPP$uPPP$yPPPP$}%QTTOVQXPQYQR]SR`XQfYQ!PmR!b!_UeYm!_R!UvWdYmv!_SgZiSnapTrbtXdYmv!_QyfQ!OlS!Z|}Q!^!PR!`![Rl]V!Y|![!aV!X|![!aQVOR^VQpaR!QpQtbR!StQweR!VwQiZRziQ}lR!]}TUOVToapTsbtR[RThZi",
  nodeNames: "⚠ LineComment File StringEntry EntryType EntryOpen StringName Value ValueAtom BracedValue Escape QuotedValue Number StringRef Concat EntryClose PreambleEntry CommentEntry Entry EntryKey Field FieldName",
  maxTerm: 50,
  skippedNodes: [0,1],
  repeatNodeCount: 6,
  tokenData: "3v~RtOX#cXY${YZ${Z]#c]^${^p#cpq${qr#crs&Vst&rtu#cuv'gvx#cxy*[yz+Pz|#c|}+t}!Q#c!Q![,i![!_#c!_!`-d!`!b#c!b!c.X!c!}0R!}#O#c#O#P3R#P#R#c#R#S0R#S#T#c#T#o0R#o#p3l#p#q#c#q#r3q#r;'S#c;'S;=`$u<%lO#cY#lWvQzW!QQOr#crs$Us#O#c#P#o#c#p#q#c#r;'S#c;'S;=`$u<%lO#cQ$]UvQ!QQO#O$U#P#o$U#p#q$U#r;'S$U;'S;=`$o<%lO$UQ$rP;=`<%l$UY$xP;=`<%l#c_%W_nTvQzW!QQOX#cXY${YZ${Z]#c]^${^p#cpq${qr#crs$Us#O#c#P#o#c#p#q#c#r;'S#c;'S;=`$u<%lO#cZ&`UxXvQ!QQO#O$U#P#o$U#p#q$U#r;'S$U;'S;=`$o<%lO$UZ&}W^PvQzW!QQOr#crs$Us#O#c#P#o#c#p#q#c#r;'S#c;'S;=`$u<%lO#c_'r]PTvQzW!QQOY'gYZ#cZr'grs(ks#O'g#O#P)g#P#o'g#o#p)g#p#q'g#q#r)g#r;'S'g;'S;=`*U<%lO'gV(tZPTvQ!QQOY(kYZ$UZ#O(k#O#P)g#P#o(k#o#p)g#p#q(k#q#r)g#r;'S(k;'S;=`*O<%lO(kT)lSPTOY)gZ;'S)g;'S;=`)x<%lO)gT){P;=`<%l)gV*RP;=`<%l(k_*XP;=`<%l'gZ*gWrPvQzW!QQOr#crs$Us#O#c#P#o#c#p#q#c#r;'S#c;'S;=`$u<%lO#cZ+[W{PvQzW!QQOr#crs$Us#O#c#P#o#c#p#q#c#r;'S#c;'S;=`$u<%lO#cZ,PW!SPvQzW!QQOr#crs$Us#O#c#P#o#c#p#q#c#r;'S#c;'S;=`$u<%lO#cZ,tY[PvQzW!QQOr#crs$Us!Q#c!Q![,i![#O#c#P#o#c#p#q#c#r;'S#c;'S;=`$u<%lO#cZ-oWtPvQzW!QQOr#crs$Us#O#c#P#o#c#p#q#c#r;'S#c;'S;=`$u<%lO#cZ.bZvQzW!QQOr#crs$Us!c#c!c!}/T!}#O#c#P#T#c#T#o/T#p#q#c#r;'S#c;'S;=`$u<%lO#cZ/`ZSPvQzW!QQOr#crs$Us!c#c!c!}/T!}#O#c#P#T#c#T#o/T#p#q#c#r;'S#c;'S;=`$u<%lO#c_0`c!RSsPvQzW!QQOr#crs$Us}#c}!O0R!O!P1k!P!Q1k!Q![0R![!]1k!]!c#c!c!}0R!}#O#c#P#R#c#R#S0R#S#T#c#T#o0R#p#q#c#r;'S#c;'S;=`$u<%lO#c^1vc!RSvQzW!QQOr#crs$Us}#c}!O1k!O!P1k!P!Q1k!Q![1k![!]1k!]!c#c!c!}1k!}#O#c#P#R#c#R#S1k#S#T#c#T#o1k#p#q#c#r;'S#c;'S;=`$u<%lO#c~3URO;'S3_;'S;=`3d;=`O3_~3dOY~~3iPY~;=`<%l3_~3qOq~~3vOw~",
  tokenizers: [0, 1, 2, 3],
  topRules: {"File":[0,2]},
  specialized: [{term: 4, get: (value) => spec_EntryType[value] || -1}],
  tokenPrec: 229
})
